Ai cv update bugs
NextGen-Internship/AI_CV_Template pull request #40
Opened 2024-02-15 15:04 UTC by pavelpetrov47

2024-02-15 15:06 UTC, PetkoLyuts approved these changes

2024-02-15 15:07 UTC, PetkoLyuts commented on AI_CV_React/frontend/src/cv/CvTemplate.jsx
> +    console.log("Field:", field);
logs

2024-02-15 15:09 UTC, PetkoLyuts approved these changes

2024-02-15 15:09 UTC, mkanevv requested changes

2024-02-15 15:09 UTC, mkanevv commented on AI_CV_JAVA/src/main/java/com/example/AI_CV_JAVA/service/impl/PersonServiceImpl.java
> +        }
Add error handling

2024-02-15 15:09 UTC, mkanevv commented on AI_CV_JAVA/src/main/java/com/example/AI_CV_JAVA/service/impl/PdfServiceImpl.java
> +            technologies.add(technology);
Error handling

2024-02-16 08:16 UTC, pavelpetrov47 commented on AI_CV_JAVA/src/main/java/com/example/AI_CV_JAVA/service/impl/PdfServiceImpl.java
> +            technologies.add(technology);
i dont need error handling here

2024-02-16 08:16 UTC, pavelpetrov47 commented on AI_CV_JAVA/src/main/java/com/example/AI_CV_JAVA/service/impl/PersonServiceImpl.java
> +        }
fixed

2024-02-16 09:08 UTC, mkanevv requested changes
dont forget to format

2024-02-16 09:17 UTC, pavelpetrov47 commented on AI_CV_JAVA/src/main/java/com/example/AI_CV_JAVA/service/impl/PdfServiceImpl.java
> +            }else{
all set

2024-02-16 09:42 UTC, mkanevv approved these changes

2024-02-16 12:20 UTC, merged